# Zyrex private testnet. These public keys are DEVELOPMENT ONLY.
zyrex {
  networkType = "devnet"
  node {
    mining = false
    offlineGeneration = false
    useExternalMiner = false
    stateType = "utxo"
    verifyTransactions = true
    internalMinerPollingInterval = 1s
    utxo.utxoBootstrap = false
    nipopow.nipopowBootstrap = false
  }
  chain {
    protocolVersion = 4
    genesisId = "bb994c82d023bf2cf92f88be6f9f997f280b5fb76c3f8dac875f0458dcc51531"
    addressPrefix = 80
    blockInterval = 60s
    epochLength = 16
    useLastEpochs = 8
    initialDifficultyHex = "01"
    genesisStateDigestHex = "0724b921c507ac7a2e26db34796b291200e8b28023ef6095889b71c187f979e001"
    noPremineProof = ["Zyrex ZYRX private testnet; 2026-10-08; no premine"]
    foundersPubkeys = []
    monetary {
      fixedRate = 100000000000
      fixedRatePeriod = 432000
      epochLength = 432000
      foundersInitialReward = 10000000000
      minerRewardDelay = 3
    }
    reemission {
      checkReemissionRules = false
      activationHeight = 2147483647
      reemissionStartHeight = 2147483647
    }
    zyrex {
      networkTag = 1515803204
      founderPubkeys = ["0201941e4163eae332959cf06743b28c6b9426772da7faf5a5d5a4ad8e3653595c", "027103af8e57854c8b2bfaf9cbbba7801c4f456919dad1d153c859aa774b536b23"]
    }
    voting {
      votingLength = 128
      softForkEpochs = 8
      activationEpochs = 8
      version2ActivationHeight = 0
      version2ActivationDifficultyHex = "01"
    }
    makeSnapshotEvery = 1024
  }
  wallet.checkEIP27 = false
  wallet.secretStorage.secretDir = ${zyrex.directory}"/wallet/keystore"
  voting = {}
}
scorex {
  network {
    agentName = "zyrex"
    magicBytes = [90, 89, 82, 68]
    bindAddress = "0.0.0.0:19532"
    nodeName = "zyrex-devnet"
    knownPeers = []
    peerDiscovery = false
    allowLocal = true
    upnpEnabled = false
  }
  restApi {
    bindAddress = "127.0.0.1:19555"
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
