# Zyrex mainnet NOT LAUNCHED. Fill recipients and pin a new genesis before release.
zyrex {
  networkType = "mainnet"
  node {
    mining = false
    offlineGeneration = false
    useExternalMiner = false
    stateType = "utxo"
    verifyTransactions = true
    internalMinerPollingInterval = 1s
    utxo.utxoBootstrap = false
    nipopow.nipopowBootstrap = false
  }
  chain {
    protocolVersion = 4
    addressPrefix = 48
    blockInterval = 60s
    epochLength = 2048
    useLastEpochs = 8
    initialDifficultyHex = "01"
    genesisStateDigestHex = "000000000000000000000000000000000000000000000000000000000000000000"
    noPremineProof = ["Zyrex ZYRX mainnet not launched"]
    foundersPubkeys = []
    monetary {
      fixedRate = 100000000000
      fixedRatePeriod = 432000
      epochLength = 432000
      foundersInitialReward = 10000000000
      minerRewardDelay = 1440
    }
    reemission {
      checkReemissionRules = false
      activationHeight = 2147483647
      reemissionStartHeight = 2147483647
    }
    zyrex {
      networkTag = 1515803224
      founderPubkeys = []
    }
    voting {
      votingLength = 128
      softForkEpochs = 8
      activationEpochs = 8
      version2ActivationHeight = 0
      version2ActivationDifficultyHex = "01"
    }
    makeSnapshotEvery = 1024
  }
  wallet.checkEIP27 = false
  wallet.secretStorage.secretDir = ${zyrex.directory}"/wallet/keystore"
  voting = {}
}
scorex {
  network {
    agentName = "zyrex"
    magicBytes = [90, 89, 82, 88]
    bindAddress = "0.0.0.0:19530"
    nodeName = "zyrex-mainnet"
    knownPeers = []
    peerDiscovery = false
    upnpEnabled = false
  }
  restApi {
    bindAddress = "127.0.0.1:19553"
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
