# Zyrex public testnet. Test coins and founder keys are for testing only.
zyrex {
  networkType = "testnet"
  node {
    mining = false
    offlineGeneration = false
    useExternalMiner = false
    stateType = "utxo"
    verifyTransactions = true
    internalMinerPollingInterval = 1s
    utxo.utxoBootstrap = false
    nipopow.nipopowBootstrap = false
  }
  chain {
    protocolVersion = 4
    genesisId = "0f6e2d9181f10231dafa9e1aa3eb297218204e2e2c38f3c65ae0ab367629d336"
    addressPrefix = 64
    blockInterval = 60s
    epochLength = 64
    useLastEpochs = 8
    initialDifficultyHex = "0100000000"
    genesisStateDigestHex = "1c92500f949411624ca85f0e5102069fff51208c96ebd8238e4eaa56270fb92701"
    noPremineProof = ["Zyrex public testnet; 2026-10-08; no premine"]
    foundersPubkeys = []
    monetary {
      fixedRate = 100000000000
      fixedRatePeriod = 432000
      epochLength = 432000
      foundersInitialReward = 10000000000
      minerRewardDelay = 5
    }
    reemission {
      checkReemissionRules = false
      activationHeight = 2147483647
      reemissionStartHeight = 2147483647
    }
    zyrex {
      networkTag = 1515803220
      founderPubkeys = [
      "02764393903f6555d6409620ea84dd60592f70ad5d4218562bcff63fe2e4403a09",
      "03e0c8ba48a1f9802acadfcf0172253c4605d1d9783f5e6af554a9b86b5c464512"
    ]
    }
    voting {
      votingLength = 128
      softForkEpochs = 8
      activationEpochs = 8
      version2ActivationHeight = 0
      version2ActivationDifficultyHex = "01"
    }
    makeSnapshotEvery = 1024
  }
  wallet.checkEIP27 = false
  wallet.secretStorage.secretDir = ${zyrex.directory}"/wallet/keystore"
  voting = {}
}
scorex {
  network {
    agentName = "zyrex"
    magicBytes = [90, 89, 82, 84]
    bindAddress = "0.0.0.0:19531"
    nodeName = "zyrex-testnet"
    knownPeers = ["stratum.zyrexchain.com:19531", "stratum.zyrexchain.com:19533"]
    peerDiscovery = false
    allowLocal = true
    upnpEnabled = false
  }
  restApi {
    bindAddress = "127.0.0.1:19554"
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
