# Local private testnet node 1.
zyrex.node.mining = true
zyrex.node.offlineGeneration = true
scorex.network.nodeName = "zyrex-private-1"
scorex.network.bindAddress = "0.0.0.0:19532"
scorex.network.declaredAddress = "172.29.95.11:19532"
scorex.network.knownPeers = ["172.29.95.12:19532", "172.29.95.13:19532"]
scorex.restApi.bindAddress = "0.0.0.0:19555"
