# Start with --devnet. Initialize a wallet, or set a compressed mining public key.
zyrex.node.mining = true
zyrex.node.offlineGeneration = true
zyrex.node.useExternalMiner = true
zyrex.node.miningPubKeyHex = ${?ZYREX_MINING_PUBLIC_KEY}
