import copy
import json
import tempfile
import threading
import unittest
import urllib.error
import urllib.request
from pathlib import Path
from unittest.mock import Mock
from server import Handler, Index, Server, address_script, encode_address, script_address
from pow import address_bytes


class CanonicalIndexTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        source = Path(__file__).resolve().parents[1] / 'src/main/resources/genesis/testnet.json'
        self.genesis = json.loads(source.read_text())
        self.config = {'genesisId': self.genesis['header']['id'], 'database': self.directory.name + '/index.sqlite'}
        self.index = Index(self.config)
        self.index.append(self.genesis)
        self.founder = self.genesis['blockTransactions']['transactions'][0]['outputs'][2]
        self.address = script_address(self.founder['ergoTree'])

    def tearDown(self):
        self.index.db.close()
        self.directory.cleanup()

    def next_block(self, ident='a', parent=None):
        script = self.genesis['blockTransactions']['transactions'][0]['outputs'][3]['ergoTree']
        return {'header': {'height': 2, 'id': ident*64, 'parentId': parent or self.config['genesisId']},
                'blockTransactions': {'transactions': [{'id': 'b'*64, 'inputs': [{'boxId': self.founder['boxId']}],
                    'outputs': [{'boxId': 'c'*64, 'value': self.founder['value'], 'ergoTree': script}]}]}}

    def test_native_genesis_balances_use_exact_integer_strings(self):
        account = self.index.query('/api/address/' + self.address)
        self.assertEqual(account['balanceNano'], '5000000000')
        self.assertEqual(address_bytes(self.address)[0], 65)
        reserve = self.genesis['blockTransactions']['transactions'][0]['outputs'][0]
        stored = self.index.query('/api/block/1')
        self.assertEqual(stored['blockTransactions']['transactions'][0]['outputs'][0]['value'], str(reserve['value']))

    def test_p2s_alias_of_p2pk_has_the_same_boxes_and_balance(self):
        alias = encode_address(b'\x43' + bytes.fromhex(self.founder['ergoTree']))
        self.assertEqual(address_script(alias), address_script(self.address))
        expected = self.index.query('/api/address/' + self.address)
        actual = self.index.query('/api/address/' + alias)
        self.assertEqual(actual['balanceNano'], expected['balanceNano'])
        self.assertEqual(actual['boxes'], expected['boxes'])
        self.index.append(self.next_block())
        self.assertEqual(self.index.query('/api/address/' + alias)['balanceNano'], '0')
        self.index.rollback(1)
        self.assertEqual(self.index.query('/api/address/' + alias)['balanceNano'], '5000000000')

    def test_native_p2sh_fixture_is_found_spent_and_restored_after_reorg(self):
        # Generated by Pay2SHAddress in the pinned SDK, independently of this explorer.
        address = 'ZRX3znEGfcaKmXJEkwow5UQZSqtULDCuDwES5n9k6D8'
        script = ('00ea02d193b4cbe4e37e0e040004300e18'
                  '000102030405060708090a0b0c0d0e0f1011121314151617d4087e')
        self.assertEqual(address_script(address), script)
        self.assertEqual(script_address(script), address)
        alias = encode_address(b'\x43' + bytes.fromhex(script))
        block = self.next_block()
        block['blockTransactions']['transactions'][0]['outputs'][0]['ergoTree'] = script
        self.index.append(block)
        # Existing indexes stored this script as P2S; script lookup also repairs their queries.
        with self.index.db:
            self.index.db.execute('UPDATE boxes SET address=? WHERE id=?', (alias, 'c'*64))
        self.assertEqual(self.index.query('/api/address/' + address)['balanceNano'], '5000000000')
        self.assertEqual(self.index.query('/api/address/' + alias)['balanceNano'], '5000000000')
        spent = copy.deepcopy(block)
        spent['header'].update(height=3, id='d'*64, parentId='a'*64)
        tx = spent['blockTransactions']['transactions'][0]
        tx.update(id='e'*64, inputs=[{'boxId': 'c'*64}])
        tx['outputs'][0].update(boxId='f'*64, ergoTree=self.founder['ergoTree'])
        self.index.append(spent)
        self.assertEqual(self.index.query('/api/address/' + address)['balanceNano'], '0')
        self.assertEqual(self.index.query('/api/address/' + address)['boxes'][0]['spent_by'], 'e'*64)
        self.index.rollback(2)
        self.assertEqual(self.index.query('/api/address/' + address)['balanceNano'], '5000000000')
        self.index.rollback(1)
        self.assertEqual(self.index.query('/api/address/' + address)['boxes'], [])

    def test_second_native_p2sh_vector_and_indexed_script_query(self):
        address = 'ZRX43QwdtCpNXcocZ1e6Z2SobUkzuhjpsSPMJZXtRJa'
        script = '00ea02d193b4cbe4e37e0e040004300e18' + 'ff'*24 + 'd4087e'
        self.assertEqual(address_script(address), script)
        self.assertEqual(script_address(script), address)
        plan = self.index.db.execute(
            'EXPLAIN QUERY PLAN SELECT value FROM boxes WHERE script=? COLLATE NOCASE AND spent_by IS NULL',
            (script,)).fetchall()
        self.assertTrue(any('boxes_script' in row[3] for row in plan))

    def test_bad_checksum_foreign_network_and_bad_payloads_are_rejected(self):
        bad_checksum = self.address[:-1] + ('1' if self.address[-1] != '1' else '2')
        invalid = [bad_checksum, encode_address(b'\x31' + address_bytes(self.address)[1:]),
                   encode_address(b'\x42' + b'\0'*23), encode_address(b'\x43' + b'\0'),
                   encode_address(b'\x41' + b'\x02' + b'\xff'*32)]
        for address in invalid:
            with self.subTest(address=address), self.assertRaises(ValueError):
                self.index.query('/api/address/' + address)

    def test_invalid_p2sh_request_returns_http_error_instead_of_zero_balance(self):
        server = Server(('127.0.0.1', 0), Handler)
        server.index = self.index
        worker = threading.Thread(target=server.serve_forever, daemon=True)
        worker.start()
        try:
            address = encode_address(b'\x42' + b'\0'*23)
            with self.assertRaises(urllib.error.HTTPError) as caught:
                urllib.request.urlopen(f'http://127.0.0.1:{server.server_port}/api/address/{address}')
            self.assertEqual(caught.exception.code, 400)
            error = json.loads(caught.exception.read())
            self.assertEqual(error['error'], 'Invalid P2SH script hash length')
            self.assertNotIn('balanceNano', error)
        finally:
            server.shutdown()
            server.server_close()
            worker.join(timeout=2)

    def test_spend_and_rollback_restore_balance_and_remove_orphan_transactions(self):
        self.index.append(self.next_block())
        self.assertEqual(self.index.query('/api/address/' + self.address)['balanceNano'], '0')
        self.index.rollback(1)
        self.assertEqual(self.index.query('/api/address/' + self.address)['balanceNano'], '5000000000')
        with self.assertRaises(LookupError):
            self.index.query('/api/tx/' + 'b'*64)
        self.index.append(self.next_block(ident='d'))
        self.assertEqual(self.index.height(), 2)

    def test_missing_input_rolls_back_the_entire_block(self):
        block = self.next_block()
        block['blockTransactions']['transactions'][0]['inputs'][0]['boxId'] = 'f'*64
        with self.assertRaises(ValueError):
            self.index.append(block)
        self.assertEqual(self.index.height(), 1)
        self.assertEqual(self.index.query('/api/address/' + self.address)['balanceNano'], '5000000000')

    def test_foreign_database_and_network_are_rejected(self):
        with self.assertRaises(ValueError):
            Index(dict(self.config, genesisId='f'*64))
        self.index.rpc = Mock(return_value={'network': 'devnet', 'genesisBlockId': self.config['genesisId']})
        with self.assertRaises(ValueError):
            self.index.sync()

    def test_canonical_fork_replaces_index_without_mixing_balances(self):
        self.index.append(self.next_block())
        alternate = self.next_block(ident='d')
        def rpc(path):
            if path == '/info':
                return {'network': 'testnet', 'genesisBlockId': self.config['genesisId'], 'fullHeight': 2}
            if path.endswith('toHeight=1'):
                return [self.genesis['header']]
            if path.endswith('toHeight=2'):
                return [alternate['header']]
            if path == '/blocks/' + 'd'*64:
                return alternate
            raise AssertionError(path)
        self.index.rpc = rpc
        self.index.sync()
        self.assertEqual(self.index.query('/api/block/2')['header']['id'], 'd'*64)
        self.assertEqual(self.index.query('/api/address/' + self.address)['balanceNano'], '0')
